# Generated by Django 5.2 on 2025-04-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautoretail', '0002_remove_car_image_carimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='make',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='mileage',
            new_name='kilometer',
        ),
    ]
