# Generated by Django 5.2 on 2025-04-16 08:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import lifeautoimport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('kilometer', models.PositiveIntegerField(verbose_name='Kilometers')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=20, verbose_name='Fuel Type')),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20, verbose_name='Transmission')),
                ('engine_size', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Engine Size (L)')),
                ('auction_house', models.CharField(max_length=100, verbose_name='Auction House')),
                ('auction_date', models.DateField(verbose_name='Auction Date')),
                ('auction_location', models.CharField(max_length=100, verbose_name='Auction Location')),
                ('auction_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Auction Price ($)')),
                ('auction_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Auction Fee ($)')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('shipping_company', models.CharField(blank=True, max_length=100, verbose_name='Shipping Company')),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Shipping Cost ($)')),
                ('shipping_departure_date', models.DateField(blank=True, null=True, verbose_name='Shipping Departure Date')),
                ('shipping_arrival_date', models.DateField(blank=True, null=True, verbose_name='Shipping Arrival Date')),
                ('port_of_loading', models.CharField(blank=True, max_length=100, verbose_name='Port of Loading')),
                ('port_of_discharge', models.CharField(blank=True, max_length=100, verbose_name='Port of Discharge')),
                ('insurance_company', models.CharField(blank=True, max_length=100, verbose_name='Insurance Company')),
                ('insurance_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Insurance Cost ($)')),
                ('insurance_policy_number', models.CharField(blank=True, max_length=50, verbose_name='Insurance Policy Number')),
                ('customs_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Customs Cost ($)')),
                ('tax_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tax Cost ($)')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Cost ($)')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Selling Price ($)')),
                ('status', models.CharField(choices=[('auction', 'At Auction'), ('purchased', 'Purchased'), ('shipping', 'In Shipping'), ('customs', 'In Customs'), ('arrived', 'Arrived'), ('sold', 'Sold')], default='auction', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Imported Car',
                'verbose_name_plural': 'Imported Cars',
                'ordering': ['-auction_date'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=lifeautoimport.models.car_image_path, verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('image_type', models.CharField(choices=[('exterior', 'Exterior'), ('interior', 'Interior'), ('engine', 'Engine'), ('chassis', 'Chassis'), ('damage', 'Damage'), ('document', 'Document'), ('other', 'Other')], max_length=50, verbose_name='Image Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lifeautoimport.importedcar')),
            ],
            options={
                'verbose_name': 'Car Image',
                'verbose_name_plural': 'Car Images',
            },
        ),
        migrations.CreateModel(
            name='CarDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='car_document_path', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Document')),
                ('document_type', models.CharField(choices=[('auction', 'Auction Document'), ('invoice', 'Invoice'), ('bill_of_lading', 'Bill of Lading'), ('insurance', 'Insurance Document'), ('customs', 'Customs Document'), ('registration', 'Registration Document'), ('other', 'Other')], max_length=50, verbose_name='Document Type')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lifeautoimport.importedcar')),
            ],
            options={
                'verbose_name': 'Car Document',
                'verbose_name_plural': 'Car Documents',
            },
        ),
    ]
