# Generated by Django 5.2 on 2025-04-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautoimport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedcar',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Selling Price ($)'),
        ),
        migrations.AlterField(
            model_name='importedcar',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Cost ($)'),
        ),
    ]
