# Generated by Django 5.2 on 2025-04-16 12:08

import django.core.validators
import lifeautoimport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautoimport', '0002_alter_importedcar_selling_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importedcar',
            options={'ordering': ['-auction_date'], 'permissions': [('view_net_profit', 'Can view net profit')], 'verbose_name': 'Imported Car', 'verbose_name_plural': 'Imported Cars'},
        ),
        migrations.AlterField(
            model_name='cardocument',
            name='document',
            field=models.FileField(upload_to=lifeautoimport.models.car_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Document'),
        ),
    ]
