# Generated by Django 5.2 on 2025-04-16 12:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautoimport', '0003_alter_importedcar_options_alter_cardocument_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=django.utils.timezone.now, verbose_name='Month')),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Profit ($)')),
                ('car_count', models.PositiveIntegerField(verbose_name='Number of Cars Sold')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfitShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Profit Percentage (%)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin User')),
            ],
        ),
    ]
