# Generated by Django 5.2 on 2025-04-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautoimport', '0004_monthlyprofit_userprofitshare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyProfit',
        ),
        migrations.DeleteModel(
            name='UserProfitShare',
        ),
    ]
