# Generated by Django 5.2 on 2025-04-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautoimport', '0007_remove_client_phone_client_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedcar',
            name='condition_type',
            field=models.CharField(choices=[('clean_title', 'Clean Title'), ('normal_wear', 'Normal Wear'), ('exceeds_mechanical_limits', 'Exceeds Mechanical Limits'), ('biohazard', 'Biohazard / Chemical'), ('burn_engine', 'Burn - Engine'), ('burn_interior', 'Burn - Interior'), ('burn_exterior', 'Burn - Exterior'), ('damage_history', 'Damage History'), ('frame_damage', 'Frame Damage'), ('hail_damage', 'Hail Damage'), ('mechanical', 'Mechanical'), ('mileage_discrepancy', 'Mileage Discrepancy'), ('partial_repair', 'Partial Repair'), ('rejected_repair', 'Rejected Repair'), ('rollover', 'Rollover'), ('side_damage', 'Side Damage'), ('stripped', 'Stripped'), ('theft_recovery', 'Theft Recovery'), ('undercarriage_damage', 'Undercarriage Damage'), ('vandalism', 'Vandalism'), ('water_flood', 'Water / Flood'), ('all_over_damage', 'All Over Damage')], default='clean_title', max_length=50, verbose_name='Vehicle Condition Type'),
        ),
        migrations.AddField(
            model_name='importedcar',
            name='key',
            field=models.CharField(blank=True, choices=[('Has Key', 'Has Key'), ('Missing', 'Missing'), ('Other', 'Other')], default='Other', max_length=50, verbose_name='Key'),
        ),
    ]
