# Generated by Django 5.2 on 2025-04-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautoimport', '0008_importedcar_condition_type_importedcar_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedcar',
            name='auction_country',
            field=models.CharField(choices=[('USA', 'USA'), ('Canada', 'Canada'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Netherlands', 'Netherlands'), ('Belgium', 'Belgium'), ('United Kingdom', 'United Kingdom'), ('Turkey', 'Turkey'), ('United Arab Emirates', 'United Arab Emirates'), ('Japan', 'Japan'), ('South Korea', 'South Korea'), ('China', 'China'), ('Russia', 'Russia'), ('Spain', 'Spain'), ('Poland', 'Poland'), ('Georgia', 'Georgia'), ('Ukraine', 'Ukraine')], default='USA', max_length=50, verbose_name='Auction Country'),
        ),
        migrations.AlterField(
            model_name='importedcar',
            name='auction_fee',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Auction Fee (zł)'),
        ),
        migrations.AlterField(
            model_name='importedcar',
            name='auction_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Auction Price (zł)'),
        ),
        migrations.AlterField(
            model_name='importedcar',
            name='condition_type',
            field=models.CharField(choices=[('clean_title', 'Clean Title'), ('normal_wear', 'Normal Wear'), ('exceeds_mechanical_limits', 'Exceeds Mechanical Limits'), ('biohazard', 'Biohazard / Chemical'), ('burn_engine', 'Burn - Engine'), ('burn_interior', 'Burn - Interior'), ('burn_exterior', 'Burn - Exterior'), ('damage_history', 'Damage History'), ('frame_damage', 'Frame Damage'), ('hail_damage', 'Hail Damage'), ('mechanical', 'Mechanical'), ('mileage_discrepancy', 'Mileage Discrepancy'), ('partial_repair', 'Partial Repair'), ('rejected_repair', 'Rejected Repair'), ('rollover', 'Rollover'), ('side_damage', 'Side Damage'), ('stripped', 'Stripped'), ('theft_recovery', 'Theft Recovery'), ('undercarriage_damage', 'Undercarriage Damage'), ('vandalism', 'Vandalism'), ('water_flood', 'Water / Flood'), ('all_over_damage', 'All Over Damage')], max_length=50, verbose_name='Vehicle Condition Type'),
        ),
        migrations.AlterField(
            model_name='importedcar',
            name='customs_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Customs Cost (zł)'),
        ),
        migrations.AlterField(
            model_name='importedcar',
            name='insurance_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Insurance Cost (zł)'),
        ),
        migrations.AlterField(
            model_name='importedcar',
            name='key',
            field=models.CharField(blank=True, choices=[('Has Key', 'Has Key'), ('Missing', 'Missing'), ('Other', 'Other')], max_length=50, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='importedcar',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Selling Price (zł)'),
        ),
        migrations.AlterField(
            model_name='importedcar',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Shipping Cost (zł)'),
        ),
        migrations.AlterField(
            model_name='importedcar',
            name='tax_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tax Cost (zł)'),
        ),
        migrations.AlterField(
            model_name='importedcar',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Cost (zł)'),
        ),
    ]
