# Generated by Django 5.2 on 2025-04-17 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautoimport', '0009_importedcar_auction_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, default='Unknown', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits and be between 9 and 15 characters.', regex='^\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='importedcar',
            name='auction_country',
            field=models.CharField(choices=[('USA', 'USA'), ('Canada', 'Canada'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Netherlands', 'Netherlands'), ('Belgium', 'Belgium'), ('United Kingdom', 'United Kingdom'), ('Turkey', 'Turkey'), ('United Arab Emirates', 'United Arab Emirates'), ('Japan', 'Japan'), ('South Korea', 'South Korea'), ('China', 'China'), ('Russia', 'Russia'), ('Spain', 'Spain'), ('Poland', 'Poland'), ('Georgia', 'Georgia'), ('Ukraine', 'Ukraine')], max_length=50, verbose_name='Auction Country'),
        ),
    ]
