# Generated by Django 5.2 on 2025-04-17 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautoimport', '0010_alter_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_contacted',
            field=models.BooleanField(default=False, verbose_name='Is Contacted'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AddField(
            model_name='client',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits and be between 9 and 15 characters.', regex='^\\d{9,15}$')], verbose_name='Phone Number'),
        ),
    ]
