# Generated by Django 5.2 on 2025-04-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautoimport', '0013_alter_client_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country_code',
            field=models.CharField(blank=True, default='+48', max_length=10, null=True, verbose_name='Country Index'),
        ),
    ]
