# Generated by Django 5.2 on 2025-04-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautoimport', '0015_vehicleadvertisament_vehicleadvertisementimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleadvertisementimage',
            name='description',
        ),
    ]
