# Generated by Django 5.2 on 2025-04-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautoimport', '0016_remove_vehicleadvertisementimage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_contacted',
        ),
        migrations.RemoveField(
            model_name='client',
            name='message',
        ),
    ]
