# Generated by Django 5.2 on 2025-04-24 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautoimport', '0017_remove_client_is_contacted_remove_client_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInquiryImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('is_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='lifeautoimport.vehicleadvertisament')),
            ],
        ),
    ]
