# Generated by Django 5.2 on 2025-04-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautoimport', '0018_customerinquiryimport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleadvertisementimage',
            name='advertisement',
        ),
        migrations.DeleteModel(
            name='CustomerInquiryImport',
        ),
        migrations.DeleteModel(
            name='VehicleAdvertisament',
        ),
        migrations.DeleteModel(
            name='VehicleAdvertisementImage',
        ),
    ]
