# Generated by Django 5.2 on 2025-04-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('languages', models.JSONField()),
                ('date_of_birth', models.DateField()),
                ('street', models.CharField(max_length=255)),
                ('floor_number', models.CharField(blank=True, max_length=20, null=True)),
                ('postcode', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('has_bank_account', models.BooleanField()),
                ('bank_account_number', models.CharField(blank=True, max_length=34, null=True)),
                ('is_student', models.BooleanField()),
                ('is_over_26', models.BooleanField()),
                ('has_company', models.BooleanField()),
                ('apps', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
