# Generated by Django 5.2 on 2025-05-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautopartner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercarslist',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive'), ('Pending', 'Pending'), ('Expired', 'Expired')], max_length=100, verbose_name='License Status'),
        ),
    ]
