# Generated by Django 5.2 on 2025-04-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautopartner', '0002_alter_registrationpartner_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationpartner',
            name='apps',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationpartner',
            name='languages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
