"""
Django settings for lifeauto project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9yw@$c&%-wv8eofzs5nixym#-6=t!0@%eb#7o)wr9zs!ijgdqk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lifeautopartner',
    'lifeautoimport',
    'lifeautoretail',
    'lifeautovisitpage',
    'lifeautocommersial',
    'lifeautorent',
    'lifeautoreport',
    'corsheaders',
    'rest_framework',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = 'lifeauto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lifeauto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Europe/Warsaw"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/




STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True


MEDIA_URL = '/media/'  
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

JAZZMIN_SETTINGS = {

    "custom_css": "logo/custom.css",
    "custom_js": "logo/custom.js",
    "site_title": "LifeAuto Admin",
    "site_header": "LifeAuto",
    "welcome_sign": "Welcome to the LifeAuto Admin Panel",
    "copyright": "LifeAuto ",
    "site_logo": "logo/logofull.png",
    "site_logo_classes": "img-circle",
    "show_ui_builder": False,
    "search_model": ["lifeautoretail.Car", "lifeautopartner.RegistrationPartner"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "lifeautorent.Bike": "fa-solid fa-bicycle",
        "lifeautorent.Car": "fa-solid fa-car",
        "lifeautorent.EBike": "fa-solid fa-motorcycle",
        "lifeautorent.Scooter": "fa-solid fa-person-biking",
        "lifeautorent.Client": "fa-solid fa-address-card",
        "lifeautopartner.RegistrationPartner": "fa-solid fa-address-card",
        "lifeautopartner.PartnerCarsList": "fa-solid fa-car-side",
        "lifeautoretail.Car": "fa-solid fa-car-side",
        "lifeautoretail.CustomerInquiry": "fa-solid fa-comments-dollar",
        "lifeautovisitpage.Blog": "fa-solid fa-percent",
        "lifeautovisitpage.Contact": "fa-solid fa-comment-sms",
        "lifeautovisitpage.AllCustomersCRM": "fa-solid fa-users",
        "lifeautoimport.ImportedCar": "fa-solid fa-anchor",
        "lifeautoimport.Client": "fa-solid fa-address-card",
        "lifeautovisitpage.ImportedVehicleAdvertisament": "fa-solid fa-shop",
        "lifeautovisitpage.CustomerInquiryImport": "fa-solid fa-bell",
        "lifeautoreport.Report": "fa-solid fa-clipboard",

    },
     "topmenu_links": [       
        {"model": "auth.User"},
        {"app": "lifeautorent"},
        {"app": "lifeautoretail"},
        {"app": "lifeautovisitpage"},
        {"app": "lifeautopartner"},
        {"app": "lifeautocommersial"},
        {"app": "lifeautoimport"},
        {"name": "IT Support", "url": "https://wa.link/o8c11d", "new_window": True},
    ],
    "welcome_sign": "Welcome to the LifeAuto Admin Panel",



}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-warning",
    "accent": "accent-warning",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": True,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "sidebar_nav_small_text": True,
    "footer_fixed": True,
    "theme": "solar",
    "dark_mode_theme": "SOLAR",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-outline-success"
    },
    "actions_sticky_top": False
}

FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Security settings

# SECURE_SSL_REDIRECT = True
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True