# Generated by Django 5.2 on 2025-04-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the bike', null=True, upload_to='bikes/'),
        ),
        migrations.AddField(
            model_name='bike',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the bike currently active?'),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the car', null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the car currently active?'),
        ),
        migrations.AddField(
            model_name='ebike',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the e-bike', null=True, upload_to='ebikes/'),
        ),
        migrations.AddField(
            model_name='ebike',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the e-bike currently active?'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the scooter', null=True, upload_to='scooters/'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the scooter currently active?'),
        ),
    ]
