# Generated by Django 5.2 on 2025-04-17 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bike', to='lifeautorent.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car', to='lifeautorent.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='ebike',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebike', to='lifeautorent.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scooter', to='lifeautorent.client', verbose_name='Client'),
        ),
    ]
