# Generated by Django 5.2 on 2025-04-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0004_bike_client_car_client_ebike_client_scooter_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='message',
        ),
    ]
