# Generated by Django 5.2 on 2025-04-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0006_clientdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='expire',
            field=models.BooleanField(default=False, verbose_name='Expire?'),
        ),
    ]
