# Generated by Django 5.2 on 2025-04-17 14:55

import django.core.validators
import lifeautorent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0007_clientdocument_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='document',
            field=models.FileField(upload_to=lifeautorent.models.client_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Document'),
        ),
    ]
