# Generated by Django 5.2 on 2025-04-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0008_alter_clientdocument_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country_code',
            field=models.CharField(default='+48', max_length=10, verbose_name='Country Index'),
        ),
    ]
