# Generated by Django 5.2 on 2025-04-17 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0009_alter_client_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('payment_interests', models.CharField(blank=True, max_length=255, verbose_name='Payment Interets')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payments', to='lifeautorent.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Client Payment Interests',
                'verbose_name_plural': 'Client Payment Interests',
            },
        ),
    ]
