# Generated by Django 5.2 on 2025-04-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0011_clientpenalties'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpenalties',
            name='penalty_fee',
            field=models.CharField(blank=True, max_length=255, verbose_name='Penalty Interests'),
        ),
    ]
