# Generated by Django 5.2 on 2025-04-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0012_clientpenalties_penalty_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpayments',
            name='refundable',
            field=models.BooleanField(default=False, verbose_name='Refundable'),
        ),
    ]
