# Generated by Django 5.2 on 2025-04-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0013_clientpayments_refundable'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU Code'),
        ),
        migrations.AddField(
            model_name='car',
            name='sign_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sign Number'),
        ),
        migrations.AddField(
            model_name='car',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU Code'),
        ),
        migrations.AddField(
            model_name='ebike',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU Code'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU Code'),
        ),
        migrations.AlterField(
            model_name='clientpayments',
            name='description',
            field=models.CharField(blank=True, default='Weekly rental fee', max_length=255, verbose_name='Description'),
        ),
    ]
