# Generated by Django 5.2 on 2025-04-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0014_bike_sku_car_sign_number_car_sku_ebike_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='sign_number',
            field=models.CharField(max_length=100, verbose_name='Sign Number'),
        ),
    ]
