# Generated by Django 5.2 on 2025-04-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0015_alter_car_sign_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='license_number',
            field=models.CharField(default='N/A', help_text='License number of the car', max_length=100, verbose_name='License Number'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(help_text='Name of the car brand', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('delivery', 'For Delivery'), ('taxi', 'For Taxi')], help_text='Category of the car: Delivery/Taxi', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client who rented the car', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car', to='lifeautorent.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(help_text='Name of the car model', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_week',
            field=models.DecimalField(decimal_places=2, help_text='Weekly rental price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='seating_capacity',
            field=models.IntegerField(help_text='Number of seats'),
        ),
        migrations.AlterField(
            model_name='car',
            name='sign_number',
            field=models.CharField(help_text='Sign Number of the car', max_length=100, verbose_name='Sign Number'),
        ),
        migrations.AlterField(
            model_name='car',
            name='sku',
            field=models.CharField(blank=True, help_text='Unique SKU code for the car', max_length=50, unique=True, verbose_name='SKU Code'),
        ),
    ]
