# Generated by Django 5.2 on 2025-04-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0016_car_license_number_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='license_number',
            new_name='taxi_license_number',
        ),
    ]
