# Generated by Django 5.2 on 2025-04-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0017_rename_license_number_car_taxi_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, default='Inactive', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('delivery', 'For Delivery'), ('taxi', 'For Taxi')], help_text='Category of the car: Delivery/Taxi', max_length=10, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the car currently busy?', verbose_name='Busy'),
        ),
        migrations.AlterField(
            model_name='car',
            name='taxi_license_number',
            field=models.CharField(default='N/A', help_text='Taxi License number of the car', max_length=100, verbose_name='Taxi License Number'),
        ),
    ]
