# Generated by Django 5.2 on 2025-04-18 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0018_client_status_alter_car_category_alter_car_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'verbose_name': 'Bike', 'verbose_name_plural': 'Bikes'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='ebike',
            options={'verbose_name': 'E-Bike', 'verbose_name_plural': 'E-Bikes'},
        ),
        migrations.AlterModelOptions(
            name='scooter',
            options={'verbose_name': 'Scooter', 'verbose_name_plural': 'Scooters'},
        ),
        migrations.AlterField(
            model_name='bike',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='lifeautorent.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the product', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the product currently active?', verbose_name='Busy'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='lifeautorent.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the product', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the product currently active?', verbose_name='Busy'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_week',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU Code'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked'), ('Deleted', 'Deleted')], default='New', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='clientpayments',
            name='payment_interests',
            field=models.CharField(blank=True, max_length=255, verbose_name='Payment Interests'),
        ),
        migrations.AlterField(
            model_name='ebike',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='lifeautorent.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='ebike',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the product', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='ebike',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the product currently active?', verbose_name='Busy'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='lifeautorent.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the product', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the product currently active?', verbose_name='Busy'),
        ),
    ]
