# Generated by Django 5.2 on 2025-04-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0019_alter_bike_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the product', null=True, upload_to='rental_vehicle/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the product', null=True, upload_to='rental_vehicle/'),
        ),
        migrations.AlterField(
            model_name='ebike',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the product', null=True, upload_to='rental_vehicle/'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the product', null=True, upload_to='rental_vehicle/'),
        ),
    ]
