# Generated by Django 5.2 on 2025-04-18 13:15

import lifeautorent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0020_alter_bike_image_alter_car_image_alter_ebike_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the product', null=True, upload_to=lifeautorent.models.rental_product_image_path),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the product', null=True, upload_to=lifeautorent.models.rental_product_image_path),
        ),
        migrations.AlterField(
            model_name='ebike',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the product', null=True, upload_to=lifeautorent.models.rental_product_image_path),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the product', null=True, upload_to=lifeautorent.models.rental_product_image_path),
        ),
    ]
