# Generated by Django 5.2 on 2025-04-21 14:09

import django.core.validators
import lifeautorent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0021_alter_bike_image_alter_car_image_alter_ebike_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country_code',
            field=models.CharField(blank=True, default='+48', max_length=10, null=True, verbose_name='Country Index'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=lifeautorent.models.client_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='clientpayments',
            name='payment_interests',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Interests'),
        ),
    ]
