# Generated by Django 5.2 on 2025-04-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0022_alter_client_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='ebike',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
