# Generated by Django 5.2 on 2025-04-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautorent', '0023_bike_status_car_status_ebike_status_scooter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked'), ('Deleted', 'Deleted')], default='New', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked'), ('Deleted', 'Deleted')], default='New', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ebike',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked'), ('Deleted', 'Deleted')], default='New', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked'), ('Deleted', 'Deleted')], default='New', max_length=100, null=True, verbose_name='Status'),
        ),
    ]
