# Generated by Django 5.2 on 2025-05-14 13:48

import django.db.models.deletion
import lifeautovisitpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCustomersCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, choices=[('friend', 'Friend referance'), ('website', 'Website'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google'), ('x', 'X'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('phone', 'Phone'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('snapchat', 'Snapchat'), ('telegram', 'Telegram'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('twitch', 'Twitch'), ('forum', 'Forum'), ('blog', 'Blog'), ('podcast', 'Podcast')], max_length=100, null=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'All Customers CRM',
                'verbose_name_plural': 'All Customers CRM',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to=lifeautovisitpage.models.blog_main_image_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Promotions',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('checkmark', models.BooleanField(default=False, verbose_name='Acceped our regulations')),
                ('message_category', models.CharField(blank=True, choices=[('select', 'Select Category ...'), ('import', 'Import a vehicle'), ('rent', 'Rent a vehicle'), ('sell', 'Sell a vehicle'), ('service', 'Service'), ('insurance', 'Insurance'), ('finance', 'Finance'), ('buy', 'Buy a car'), ('general', 'General Inquiry'), ('support', 'Support Request'), ('feedback', 'Feedback')], default='other', max_length=20, null=True)),
                ('is_connected', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Customer Messages - Contact',
                'verbose_name_plural': 'Customer Messages - Contact',
            },
        ),
        migrations.CreateModel(
            name='ImportedVehicleAdvertisament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (zł)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=lifeautovisitpage.models.blog_image_upload_to)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lifeautovisitpage.blog')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInquiryImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('is_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='lifeautovisitpage.importedvehicleadvertisament')),
            ],
            options={
                'verbose_name': 'Customer Inquiry - Import',
                'verbose_name_plural': 'Customer Inquiry - Import',
            },
        ),
        migrations.CreateModel(
            name='VehicleAdvertisementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=lifeautovisitpage.models.advertisement_image_path, verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lifeautovisitpage.importedvehicleadvertisament', verbose_name='Advertisement')),
            ],
            options={
                'verbose_name': 'Vehicle Advertisement Image',
                'verbose_name_plural': 'Vehicle Advertisement Images',
            },
        ),
    ]
