# Generated by Django 5.2 on 2025-05-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautovisitpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcustomerscrm',
            name='platform',
            field=models.CharField(blank=True, choices=[('friend', 'Friend referance'), ('website', 'Website'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google'), ('x', 'X'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('phone', 'Phone'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('snapchat', 'Snapchat'), ('telegram', 'Telegram'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('twitch', 'Twitch'), ('forum', 'Forum'), ('blog', 'Blog'), ('podcast', 'Podcast')], max_length=100, null=True),
        ),
    ]
