# Generated by Django 5.2 on 2025-04-07 14:20

import lifeautovisitpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautovisitpage', '0002_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(upload_to=lifeautovisitpage.models.blog_image_upload_to),
        ),
    ]
