# Generated by Django 5.2 on 2025-04-07 14:25

import lifeautovisitpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautovisitpage', '0003_alter_blogimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to=lifeautovisitpage.models.blog_main_image_upload_to),
        ),
    ]
