# Generated by Django 5.2 on 2025-04-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautovisitpage', '0005_importedvehicleadvertisament_customerinquiryimport_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Promotions', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Customer Messages - Contact', 'verbose_name_plural': 'Customer Messages - Contact'},
        ),
        migrations.AlterModelOptions(
            name='customerinquiryimport',
            options={'verbose_name': 'Customer Inquiry - Import', 'verbose_name_plural': 'Customer Inquiry - Import'},
        ),
        migrations.AddField(
            model_name='contact',
            name='message_category',
            field=models.CharField(choices=[('import', 'Import a vehicle'), ('rent', 'Rent a vehicle'), ('sell', 'Sell a vehicle'), ('service', 'Service'), ('insurance', 'Insurance'), ('finance', 'Finance'), ('buy', 'Buy a car'), ('general', 'General Inquiry'), ('support', 'Support Request'), ('feedback', 'Feedback'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
