# Generated by Django 5.2 on 2025-04-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautovisitpage', '0006_alter_blog_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message_category',
            field=models.CharField(choices=[('import', 'Import a vehicle'), ('rent', 'Rent a vehicle'), ('sell', 'Sell a vehicle'), ('service', 'Service'), ('insurance', 'Insurance'), ('finance', 'Finance'), ('buy', 'Buy a car'), ('general', 'General Inquiry'), ('support', 'Support Request'), ('feedback', 'Feedback'), ('other', 'Other')], default='other', max_length=20, null=True),
        ),
    ]
