# Generated by Django 5.2 on 2025-04-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeautovisitpage', '0008_alter_contact_message_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_connected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
